services:
  db:
    image: mariadb:10.4
    # command: '--default-authentication-plugin=mysql_native_password'
    volumes:
      - db_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=noemiedoge
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=wordpress

  dev:
    build: .
    volumes:
      - ./wp-content/themes/noemiedoge:/var/www/html/wp-content/themes/noemiedoge
      - ./wp-content/uploads:/var/www/html/wp-content/uploads
    environment:
      - WORDPRESS_DB_HOST=db
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD=wordpress
      - WORDPRESS_DB_NAME=noemiedoge

volumes:
  db_data:
