name: Deployment
on:
  push:
    branches:
      - main
      - ci
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Setup SSH
      - name: Install SSH key to deploy
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.PRIVATE_SSH_KEY }}
      - run: ssh-keyscan ssh-noemiedoge.alwaysdata.net >> ~/.ssh/known_hosts

      - name: Bump theme version
        run: |
          sed -i -E "s/Version: (.*)/Version: \1-${GITHUB_SHA::6}/" ./wp-content/themes/noemiedoge/style.css

      # Deploy using rsync
      - run: rsync -rz ./wp-content/themes/noemiedoge noemiedoge@ssh-noemiedoge.alwaysdata.net:~/www/2023.noemiedoge.com/wp-content/themes
