name: Deployment
on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Setup deploy envionment (SSH + ruby)
      - name: Install SSH key to deploy
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.PRIVATE_SSH_KEY }}

      # Deploy using rsync
      - run: rsync -rz ./wp-content/themes/noemiedoge noemiedoge@ssh-noemiedoge.alwaysdata.net:~/www/2023.noemiedoge.com/wp-content/themes
